### ISSUE TITLE
Chat Not Saving (WSL Windows 10)

### ISSUE THREAD

**Issue by Infinitay** [TheNoFace/now_downloader#1]
I'm on Windows 10 but using WSL in order to use the bash script.

The script works properly except for that it doesn't not save chat messages. I've tried saving both manager-only and all-chat, but not save. The only thing that happens is that the terminal is flooded with the chat messages. For some reason the messages are not being redirecting the output from stdout to `chatOutPath`.

**Comment by TheNoFace** [comment]
Chat options save chats after the show's state is not `ONAIR`, so they display live chats until the show finishes.

Try to get chats of shows that has finished for test and see if chat messages are saved in chat folder.

**Comment by Infinitay** [comment]
> Chat options save chats after the show's state has changed from ONAIR to END

Oh okay. Is there any way to change this to also support saving the chat upon `SIGINT` (CTRL+C)? This is useful in cases like IU's Naver NOW show that was held today. The livestream is in fact still going on, but a _replay_ of the stream. I had to terminate the recording since I didn't want to keep recording the replay, and I don't know how long it would even replay for.

**Comment by TheNoFace** [comment]
I really want to know the interval between live and replay, but seems like there's nothing I can do about that. Actually, this script is designed to be run in crontab reguraly, so it may be inappropriate to monitor in real time.

I'll find what I can do to save chats when `SIGINT` is received, but it could take some time since there are so many things to rewrite in chat-related codes. You can check out to dev branch if you want.
